name: Auto Deploy to Server

on:
  push:
    branches:
      - master  # Specify the branch to trigger auto deployment (e.g., "main" or "master")

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy code via SSH
      run: |
        ssh -o StrictHostKeyChecking=no digital07@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/digital07/education.digital-vision-solutions.com
          git pull origin master
          # Add other deployment steps if needed
        EOF
        
